http: 
  port: 3000
  
database:
  mongodb:
    host: 
    port: 27017
    userName: 
    password: 
  database: 
  postgres:
    host: ep-small-wood-198254.ap-southeast-1.aws.neon.tech
    port: 5432
    username: Prashantch265
    password: xtPGIURX83lH
    database: development

mailer:
  service: Gmail
  host: smtp.gmail.com
  port: 465
  auth:
    user: 
    pass: 
  domainName:

jwt:
  accessTokenExpiresIn: 1h
  refreshTokenExpiresIn: 2h
  accessTokenSecret: goUomoyFG1Jb2cfbear9Ml9MI9EvXqme
  refreshTokenSecret: xXLBHiQZBZp7JtWg3k5GQhnzFF40qky9

oauth:
  google:
    clientID: 927949735021-op33jcgrhh6jel07fvdr88tra59efh3r.apps.googleusercontent.com
    clientSecret: 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
  facebook:
    clientID: 842068587091290
    clientSecret: 7fa3e6994cbdc125d24d573c558462af