const db = require("../../lib/sequelize");
module.exports = {
  Role: db.roles,
  Privilege: db.privileges,
  Screen: db.screens,
  Module: db.modules,
  UserRole: db.user_role,
  ModulePrivilege: db.module_privilege,
  RSMP: db.rsmp,
  User: db.users,
  Student: db.students,
  Section: db.section,
  Batch: db.batch,
  Semester: db.semester,
  Subject: db.subjects,
  Result: db.results,
  Assessment: db.assessments,
  Teacher: db.teachers,
  ExaminationSchedule: db.examination_schedule,
  ExaminationMark: db.examination_marks,
  AssessmentMarking: db.assessment_marking,
  SemesterSection: db.semester_section,
  SemesterStudent: db.semester_student,
};
