const db = require("../../lib/sequelize");
module.exports = {
  User: db.users,
  Role: db.roles,
  UserRole: db.user_role,
  Student: db.students,
  Teacher: db.teachers,
  Semester: db.semester,
  Section: db.section,
  Batch: db.batch,
  Subject: db.subjects,
  Assessment: db.assessments,
  ExaminationSchedule: db.examination_schedule,
  ExaminationMark: db.examination_marks,
  AssessmentMarking: db.assessment_marking,
  SemesterSection: db.semester_section,
  SemesterStudent: db.semester_student,
  Attendance: db.attendance,
  Result: db.examination_results,
};
